//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_student
    {
        public int courseID { get; set; }
        public int studentID { get; set; }
        public int courseYearOfEnrollment { get; set; }
        public byte passed { get; set; }
        public int semesterID { get; set; }
        public Nullable<int> midtermGrade { get; set; }
        public Nullable<int> finalGrade { get; set; }
        public Nullable<int> attendanceGrade { get; set; }
        public Nullable<int> grade { get; set; }
        public int ID { get; set; }
    }
}
